site_name: Developing with RingCentral
site_url: https://github.com/ringcentral/ringcentral-api-docs
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/ringcentral-api-docs
edit_uri: tree/master/docs
docs_dir: docs

plugins:
  - git-committers:
      repository: ringcentral/ringcentral-api-docs
      branch: master
  - bootstrap-tables

theme:
  name: ringcentral
  fluid_layout: True
  suppress_nextprev: true
  shortcuts:
    - foo

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed
  - codehilite:
      linenums: "None"
  - markdown_include.include:
       base_path: docs

extra_css:
- extra.css
- css/mega-menu.css

copyright: "1999-2020 RingCentral, Inc. All rights reserved."

google_analytics: ['UA-57519112-1', 'developers.ringcentral.com']

pages:



# ---- CORE APIs ----
- 'Primary':
  - 'Voice':
    - 'Overview': 'voice/index.md'
    - 'Getting Started':
      - 'JavaScript': 'voice/quick-start/node.md'
      - 'Python': 'voice/quick-start/python.md'
      - 'PHP': 'voice/quick-start/php.md'
      - 'Java': 'voice/quick-start/java.md'
      - 'C#': 'voice/quick-start/c-sharp.md'
      - 'Ruby': 'voice/quick-start/ruby.md'
    - 'Placing Calls':
      - 'RingOut': 'voice/ringout.md'
      - 'WebRTC': 'voice/webrtc.md'
      - 'URI Scheme': 'voice/uri-scheme.md'
    - 'Call Routing':
      - 'Overview': 'voice/call-routing/index.md'
      - 'Get Started': 'voice/call-routing/get-started.md'
      - 'Answering Rules Overview': 'voice/call-routing/manual/answering-rules.md'
      - 'User Answering Rules': 'voice/call-routing/manual/user-answering-rules.md'
      - 'Company Answering Rules': 'voice/call-routing/manual/company-answering-rules.md'
      - 'Call Queues': 'voice/call-routing/manual/call-queues.md'
      - 'Call Forwarding/Flipping': 'voice/call-routing/manual/call-forwarding.md'
    - 'Call Control':
      - 'Overview': 'voice/call-control.md'
      - 'Finding active calls': 'voice/finding-active-calls.md'
      - 'Detecting state changes': 'voice/call-control-sessions.md'
      - 'Pre-call Control': 'voice/pre-call-control.md'
      - 'Active-call Control': 'voice/active-call-control.md'
      - 'Call Monitoring': 'voice/supervision.md'
      - 'Telephony Session Notifications': 'voice/telephony-session-notifications.md'
    - 'Call Logs':
      - 'Reading Call Log Data': 'voice/call-log/reading-call-log.md'
      - 'Data Types': 'voice/call-log/api.md'
      - 'Detailed Call Log Data': 'voice/call-log/details.md'
      - 'Data Archival': 'voice/call-log/archival.md'
      - 'Call Recordings': 'voice/call-log/recordings.md'
      - 'Synchronization': 'voice/call-log/sync.md'
      - 'Best Practices': 'voice/call-log/best-practices.md'
      - 'Access Control': 'voice/call-log/access.md'
    - 'Call Analytics':
      - 'Calculating Call Metrics': 'voice/calculating-call-time-metrics.md'
    - 'Sample Applications':
      - 'Building a Web Phone with WebRTC': 'https://ringcentral-tutorials.github.io/getting-started-with-webrtc-js-demo/'
      - 'Call Log Analytics for iOS': 'https://ringcentral-tutorials.github.io/calllog-analytics-swift-demo/'
      - 'Call Log Visualizations': 'https://ringcentral-tutorials.github.io/calllog-visualization-nodejs-demo/'
      - 'Call Recording Push Notification': 'https://ringcentral-tutorials.github.io/callrecording-notification-node/'
  - 'SMS and Fax':
    - 'Overview': 'messaging/index.md'
    - 'Getting Started':
      - 'JavaScript': 'messaging/quick-start/node.md'
      - 'Python': 'messaging/quick-start/python.md'
      - 'PHP': 'messaging/quick-start/php.md'
      - 'Java': 'messaging/quick-start/java.md'
      - 'C#': 'messaging/quick-start/c-sharp.md'
      - 'Ruby': 'messaging/quick-start/ruby.md'
    - 'SMS':
      - 'Best Practices': 'messaging/sms/best-practices.md'
      - 'Sending an SMS': 'messaging/sms/sending-sms.md'
      - 'Sending an MMS': 'messaging/sms/sending-images.md'
      - 'Valid SMS Numbers': 'messaging/sms/valid-sms-numbers.md'
    - 'Fax':
      - 'Sending Faxes': 'messaging/fax/sending-faxes.md'
      - 'Multipart Formats': 'messaging/fax/fax-multipart-formats.md'
      - 'Receiving Faxes': 'messaging/fax/receiving-faxes.md'
      - 'Forwarding and Resending Faxes': 'messaging/fax/resending-faxes.md'
    - 'Pager Messages':
      - 'Sending Pager Messages': 'messaging/pager/sending-pager-messages.md'
    - 'Message Store':
      - 'Sending Messages': 'messaging/message-store/messaging.md'
      - 'Working with Message Store': 'messaging/message-store/working-with-message-store.md'
      - 'Message Synchronization': 'messaging/message-store/message-sync.md'
      - 'Modifying Message Histories': 'messaging/message-store/message-histories.md'
      - 'Message Store Export': 'messaging/message-store/message-exports-report.md'
    - 'Sample Applications':
      - 'SMS Sample App Walkthrough': 'https://ringcentral-tutorials.github.io/sms-api-nodejs-demo/'
      - 'A2P SMS Messaging': 'https://ringcentral-tutorials.github.io/a2p-sms-messaging-nodejs-demo/'
      - 'Two-factor Authentication': 'https://ringcentral-tutorials.github.io/sms-2fa-nodejs-demo/'
      - 'Custom Fax Cover Pages': 'https://ringcentral-tutorials.github.io/fax-cover-page-nodejs-demo/'

  - 'Team Messaging':
    - 'Overview': 'team-messaging/index.md'
    - 'Getting Started':
      - 'JavaScript': 'team-messaging/quick-start/node.md'
      - 'Python': 'team-messaging/quick-start/python.md'
      - 'PHP': 'team-messaging/quick-start/php.md'
      - 'Java': 'team-messaging/quick-start/java.md'
      - 'C#': 'team-messaging/quick-start/c-sharp.md'
      - 'Ruby': 'team-messaging/quick-start/ruby.md'
    - 'Manual':
      - "Composing Links": 'team-messaging/manual/links.md'
    - 'Posting Glip Messages':
      - 'Message Formatting': 'team-messaging/manual/formatting.md'
      - 'Attaching Files': 'team-messaging/manual/attaching-files.md'
      - 'Glip Webhooks': 'team-messaging/manual/webhooks.md'
    - 'Glip Compliance Export':
      - 'Compliance Export': 'team-messaging/manual/compliance-export.md'
      - 'Export File Structure': 'team-messaging/manual/compliance-export-structure.md'
    - 'Glip Bots':
      - 'Building a Bot Locally': 'team-messaging/manual/local-bots.md'
      - 'Build a Bot in Node': 'team-messaging/manual/node.md'
      - 'Bot Frameworks': 'team-messaging/manual/frameworks.md'
    - 'Sample Applications':
      - 'Glip Bot using IBM Watson and Botkit': 'https://ringcentral-tutorials.github.io/botkit-watson-bot-nodejs-demo/'
      - 'Voicemail Transcription Bot': 'https://ringcentral-tutorials.github.io/ringcentral-ai-bot/'

  - 'Meetings':
    - 'Overview': 'meetings/index.md'
    - 'Getting Started':
      - 'JavaScript': 'meetings/quick-start/node.md'
      - 'Python': 'meetings/quick-start/python.md'
      - 'PHP': 'meetings/quick-start/php.md'
      - 'Java': 'meetings/quick-start/java.md'
      - 'C#': 'meetings/quick-start/c-sharp.md'
      - 'Ruby': 'meetings/quick-start/ruby.md'
    - 'RingCentral Video': 'meetings/video.md'

  # ---- SECONDARY APIs ----
- 'Secondary':

  - 'Using the API':
      - 'Methods, endpoints and parameters': 'basics/uris.md'
      - 'Exploring the API': 'basics/explorer.md'
      - 'Using phones in sandbox': 'basics/your-rc-phone.md'
      - 'Media content': 'basics/media.md'
      - 'App permissions': 'basics/permissions.md'
      - 'URI schemes': 'basics/uri-schemes.md'
      - 'Rate limits': 'basics/rate-limits.md'
  - 'Applications':
      - 'Development Lifecycle':
          - 'Tips for your first app': 'basics/your-first-steps.md'
          - 'Create an application': 'basics/create-app.md'
          - 'Develop in sandbox': 'basics/sandbox.md'
          - 'Graduate to production': 'basics/production.md'
      - 'App Promotion':
          - 'Submit to the App Gallery': 'basics/app-gallery.md'
          - 'Update a Profile': 'basics/update-profile.md'
          - 'Checklist and Best Practices': 'basics/app-gallery-checklist.md'
          - 'Partner compatibility': 'basics/partner-compatibility.md'
          - 'Partner Brand Guidelines':
             - 'AT&T Office@Hand': 'basics/partners/att.md'
             - 'Avaya Cloud Office': 'basics/partners/aco.md'
             - 'BT Cloud Work': 'basics/partners/bt.md'
             - 'TELUS Business Connect': 'basics/partners/telus.md'
	     - 'Unify Office': 'basics/partners/atos.md'
      - 'Application Management':
          - 'Using Lead Forms': 'basics/lead-forms.md'
          - 'Install App Buttons': 'basics/install-app-button.md'

  - 'Account':
    - 'Overview': 'account/index.md'
    - 'Users and Extensions': 'account/extensions.md'
    - 'Phone Numbers': 'account/phone-numbers.md'
    - 'Call Forwarding/Flipping': 'account/call-forwarding-flipping.md'
    - 'User Feature Flags': 'account/feature-flags.md'
    - 'Custom Fields': 'account/custom-fields.md'
    - 'Presence': 'account/presence.md'

  - 'Authentication':
    - 'Overview': 'authentication/index.md'
    - 'Getting Started':
      - 'JavaScript': 'authentication/quick-start/authorization-flow/node.md'
      - 'Python': 'authentication/quick-start/authorization-flow/python.md'
      - 'PHP': 'authentication/quick-start/authorization-flow/php.md'
      - 'Java': 'authentication/quick-start/authorization-flow/java.md'
      - 'C#': 'authentication/quick-start/authorization-flow/c-sharp.md'
      - 'Ruby': 'authentication/quick-start/authorization-flow/ruby.md'
    - 'Developer Manual':
      - '3-legged OAuth Flow': 'authentication/auth-code-flow.md'
      - 'Password Flow': 'authentication/password-flow.md'
      - 'Implicit Grant Flow': 'authentication/implicit-grant-flow.md'
      - 'Using Auth Tokens': 'authentication/tokens.md'

  - 'Notifications and Events':
    - 'Overview': 'notifications/index.md'
    - 'Getting Started':
      - 'PubNub':
        - 'JavaScript': 'notifications/quick-start/pubnub/node.md'
        - 'Python': 'notifications/quick-start/pubnub/python.md'
        - 'PHP': 'notifications/quick-start/pubnub/php.md'
        - 'Java': 'notifications/quick-start/pubnub/java.md'
        - 'C#': 'notifications/quick-start/pubnub/c-sharp.md'
        - 'Ruby': 'notifications/quick-start/pubnub/ruby.md'
      - 'WebHook':
        - 'JavaScript': 'notifications/quick-start/webhook/node.md'
        - 'Python': 'notifications/quick-start/webhook/python.md'
        - 'PHP': 'notifications/quick-start/webhook/php.md'
        - 'Java': 'notifications/quick-start/webhook/java.md'
        - 'C#': 'notifications/quick-start/webhook/c-sharp.md'
        - 'Ruby': 'notifications/quick-start/webhook/ruby.md'
    - 'Webhooks':
      - 'Creating Webhooks': 'notifications/manual/webhooks.md'
      - 'Receiving Webhooks': 'notifications/manual/webhooks/receiving.md'
      - 'Configuring TLS/SSL': 'notifications/manual/webhooks/configuring-tls-ssl.md'
    - 'Mobile Push Notifications': 'notifications/manual/pubnub.md'
    - 'Sample Applications':
      - 'Create SMS Push Notification': 'https://ringcentral-tutorials.github.io/sms-api-nodejs-quickstart/'
      - 'A2P SMS Messaging': 'https://ringcentral-tutorials.github.io/a2p-sms-messaging-nodejs-demo/'

  - 'Downloads and SDKs': sdks.md
  - 'RingCentral Labs': labs.md
 
